# Generated by Django 4.2.5 on 2023-10-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="examquestion",
            name="answer",
            field=models.TextField(default=None),
        ),
    ]
