# Generated by Django 4.2.5 on 2023-10-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_examquestion_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examquestionoptions",
            name="content",
            field=models.TextField(unique=True),
        ),
    ]
