# Generated by Django 4.2.5 on 2023-10-09 04:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_examquestion_difficulty_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="examquestion",
            name="difficulty_level",
        ),
    ]
