# Generated by Django 4.2.5 on 2023-10-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0008_examquestion_difficulty_level"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookQuestionOptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="BookQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField(unique=True)),
                ("answer", models.TextField(default=None)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "correct_options",
                    models.ManyToManyField(
                        related_name="correct_options", to="main.bookquestionoptions"
                    ),
                ),
                (
                    "options",
                    models.ManyToManyField(
                        related_name="options", to="main.bookquestionoptions"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Books",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("physics", "Physics"),
                            ("chemistry", "Chemistry"),
                            ("math", "Math"),
                        ],
                        max_length=100,
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.AlterField(
            model_name="examquestion",
            name="subject",
            field=models.CharField(
                choices=[
                    ("physics", "Physics"),
                    ("chemistry", "Chemistry"),
                    ("math", "Math"),
                ],
                default="physics",
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="Exercises",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "questions",
                    models.ManyToManyField(
                        related_name="Exercises", to="main.bookquestions"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Chapters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "exercises",
                    models.ManyToManyField(
                        related_name="chapters", to="main.exercises"
                    ),
                ),
            ],
        ),
    ]
