# Generated by Django 4.2.5 on 2023-10-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0009_bookquestionoptions_bookquestions_books_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="books",
            name="chapters",
            field=models.ManyToManyField(related_name="chapters", to="main.chapters"),
        ),
    ]
