# Generated by Django 4.2.5 on 2023-10-16 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0010_books_chapters"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("physics", "Physics"),
                            ("chemistry", "Chemistry"),
                            ("math", "Math"),
                        ],
                        max_length=100,
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="main.book",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="main.chapter",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="BookQuestionOptions",
            new_name="BookQuestionOption",
        ),
        migrations.RemoveField(
            model_name="chapters",
            name="exercises",
        ),
        migrations.RemoveField(
            model_name="exercises",
            name="questions",
        ),
        migrations.RenameModel(
            old_name="BookQuestions",
            new_name="BookQuestion",
        ),
        migrations.DeleteModel(
            name="Books",
        ),
        migrations.DeleteModel(
            name="Chapters",
        ),
        migrations.DeleteModel(
            name="Exercises",
        ),
        migrations.AddField(
            model_name="exercise",
            name="questions",
            field=models.ManyToManyField(
                related_name="Exercises", to="main.bookquestion"
            ),
        ),
    ]
